name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} -t ghcr.io/${{ github.repository }}:latest .
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}:latest
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "🔄 Starting deployment..."
          
          # Login to GitHub Container Registry on server
          echo '${{ secrets.GH_PAT }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin
          
          # Navigate to application directory
          cd /opt/course-wise
          
          # Pull latest code
          git pull origin main
          
          # Pull latest image
          docker pull ghcr.io/${{ github.repository }}:latest
          
          # Stop existing containers
          docker compose -f docker-compose.prod.yml down
          
          # Start new containers
          docker compose -f docker-compose.prod.yml up -d
          
          # Wait for postgres to be ready
          sleep 10
          
          # Run database migrations
          docker compose -f docker-compose.prod.yml exec -T bot alembic upgrade head
          
          # Show logs
          docker compose -f docker-compose.prod.yml logs --tail=50
          
          echo "🎉 Deployment completed successfully!"
